### ISSUE TITLE
String ID length is bad within tags

### ISSUE THREAD

**Issue by nukeulater** [Himanshu-01/H2PC_TagExtraction#1]
https://images.discordapp.net/attachments/331105911471079424/331927557412880384/unknown.png?width=1249&height=684

Instead of flashlight, its flashligh.
Same as the others, missing the last character.

**Comment by Himanshu-01** [comment]
Yes This issue was caused becuz the last character was being replaced with a null character at the end of string
https://github.com/Himanshu-01/H2PC_TagExtraction/blob/master/BlamLib/BlamLib/IO/EndianStreams.Writer.cs#L494

Thanks to Kornman who helped me understand how Tags Read Write work so i was able to figure out the error and fix it
Refernce here:
https://github.com/Himanshu-01/H2PC_TagExtraction/blob/5299ec29f9889a7f8c03607c4dd2133f0d0814c6/BlamLib/BlamLib/TagInterface/Fields/String.cs#L533
